---
- name: Check if dosfstools is installed
  community.general.pacman:
    name: dosfstools
    state: installed

- name: Check if e2fsprogs is installed
  community.general.pacman:
    name: e2fsprogs
    state: installed

- name: Format boot partition
  ansible.builtin.command: mkfs.fat -F 32 {{ block_device }}p1

- name: Format root partition
  ansible.builtin.command: mkfs.ext4 {{ block_device }}p2
